__title__ = 'portfolio'
__description__ = 'A python cli tool to show stats on your trades and portfolio'
__version__ = '0.1.0.dev1'
__author__ = 'Rui Pires'
__author_email__ = 'ruipiresc@gmail.com'
__license__ = 'GPLv3'
__url__ = 'https://github.com/ruipiresc/ruipiresc.python.portfolio'